[package]
name = "sha_1"
version = "0.1.0"
description = "Optimised SHA-1 (pure Rust, no_std)"
keywords = ["sha", "sha1", "sha-1", "hash", "digest"]
categories = ["algorithms", "cryptography", "no-std"]
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "sha_1"
path = "src/lib.rs"

[dev-dependencies]
sha1 = "0.10"
